
export enum IdeaCategory {
  TECHNOLOGY = 'Technology',
  COMMUNITY = 'Community',
  SUSTAINABILITY = 'Sustainability',
  EDUCATION = 'Education',
  HEALTH = 'Health',
  ART = 'Art',
  INCLUSION = 'Inclusion'
}

export interface Idea {
  id: string;
  title: string;
  description: string;
  category: IdeaCategory;
  likes: number;
  dislikes: number;
  createdAt: Date;
  author: string;
  adminResponse?: string;
}

export type SupportedLanguage = 'en' | 'nl' | 'es' | 'de' | 'ar' | 'zh' | 'uk' | 'fy' | 'fr';

export interface LanguageContent {
  dashboard: string;
  ideas: string;
  admin: string;
  addIdea: string;
  export: string;
  search: string;
  generateAI: string;
  submit: string;
  titlePlaceholder: string;
  descPlaceholder: string;
  authorPlaceholder: string;
  totalIdeas: string;
  topCategory: string;
  popularTitle: string;
  noIdeas: string;
  adminLogin: string;
  adminActive: string;
  deleteConfirm: string;
  adminReply: string;
  replyPlaceholder: string;
  saveReply: string;
  topIdeasChart: string;
  timelineChart: string;
  categoryChart: string;
  engagement: string;
  activeCategories: string;
  sortBy: string;
  newest: string;
  mostLoved: string;
  bookmarks: string;
  selectIdeaPrompt: string;
  adminOverview: string;
  adminSub: string;
  tableIdea: string;
  tableAuthor: string;
  tableModeration: string;
  tableAction: string;
  delete: string;
  verify: string;
  pwdHint: string;
  aiPromptLabel: string;
  aiInputPlaceholder: string;
  aiThinking: string;
  refineAI: string;
  adoptAI: string;
  titleLabel: string;
  categoryLabel: string;
  descLabel: string;
  authorLabel: string;
  shareTitle: string;
  copyLink: string;
  linkCopied: string;
  draftSaved: string;
  categories: Record<IdeaCategory, string>;
}

export const DICTIONARY: Record<SupportedLanguage, LanguageContent> = {
  nl: {
    dashboard: "Dashboard",
    ideas: "Ideeën",
    admin: "Beheer",
    addIdea: "Idee Toevoegen",
    export: "Export (CSV)",
    search: "Zoeken...",
    generateAI: "AI Brainstorm",
    submit: "Idee Opslaan",
    titlePlaceholder: "Titel van je idee",
    descPlaceholder: "Beschrijf je innovatie...",
    authorPlaceholder: "Je naam",
    totalIdeas: "Totaal Ideeën",
    topCategory: "Top Categorie",
    popularTitle: "Meest Geliefd",
    noIdeas: "Geen ideeën gevonden.",
    adminLogin: "Admin Inlog",
    adminActive: "Beheermodus Actief",
    deleteConfirm: "Weet je zeker dat je dit wilt verwijderen?",
    adminReply: "Beheerder Reactie",
    replyPlaceholder: "Schrijf een reactie...",
    saveReply: "Opslaan",
    topIdeasChart: "Top 5 Populaire Ideeën",
    timelineChart: "Ideeën over de Tijd",
    categoryChart: "Verdeling per Categorie",
    engagement: "Totale Betrokkenheid",
    activeCategories: "Actieve Categorieën",
    sortBy: "Sorteer op:",
    newest: "Nieuwste",
    mostLoved: "Meest Geliefd",
    bookmarks: "Opgeslagen",
    selectIdeaPrompt: "Selecteer een idee voor details",
    adminOverview: "Beheer Overzicht",
    adminSub: "Systeembeheer & Moderatie",
    tableIdea: "Idee",
    tableAuthor: "Auteur",
    tableModeration: "Moderatie Reactie",
    tableAction: "Actie",
    delete: "Verwijder",
    verify: "Verifiëren",
    pwdHint: "Wachtwoord: admin123",
    aiPromptLabel: "Waar wil je over brainstormen?",
    aiInputPlaceholder: "Bijv: Duurzame energie in de wijk...",
    aiThinking: "Gemini denkt na...",
    refineAI: "Verfijn met AI",
    adoptAI: "Dit idee uitwerken",
    titleLabel: "Titel",
    categoryLabel: "Categorie",
    descLabel: "Omschrijving",
    authorLabel: "Auteur",
    shareTitle: "Deel op Social Media",
    copyLink: "Kopieer Link",
    linkCopied: "Link gekopieerd!",
    draftSaved: "Concept automatisch opgeslagen",
    categories: {
      [IdeaCategory.TECHNOLOGY]: "Technologie",
      [IdeaCategory.COMMUNITY]: "Gemeenschap",
      [IdeaCategory.SUSTAINABILITY]: "Duurzaamheid",
      [IdeaCategory.EDUCATION]: "Educatie",
      [IdeaCategory.HEALTH]: "Gezondheid",
      [IdeaCategory.ART]: "Kunst",
      [IdeaCategory.INCLUSION]: "Inclusie"
    }
  },
  en: {
    dashboard: "Dashboard",
    ideas: "Ideas",
    admin: "Admin",
    addIdea: "Add Idea",
    export: "Export (CSV)",
    search: "Search...",
    generateAI: "AI Brainstorm",
    submit: "Save Idea",
    titlePlaceholder: "Idea title",
    descPlaceholder: "Describe your innovation...",
    authorPlaceholder: "Your name",
    totalIdeas: "Total Ideas",
    topCategory: "Top Category",
    popularTitle: "Most Loved",
    noIdeas: "No ideas found.",
    adminLogin: "Admin Login",
    adminActive: "Admin Mode Active",
    deleteConfirm: "Are you sure you want to delete this?",
    adminReply: "Admin Response",
    replyPlaceholder: "Write a response...",
    saveReply: "Save",
    topIdeasChart: "Top 5 Popular Ideas",
    timelineChart: "Ideas Over Time",
    categoryChart: "Category Distribution",
    engagement: "Total Engagement",
    activeCategories: "Active Categories",
    sortBy: "Sort by:",
    newest: "Newest",
    mostLoved: "Most Loved",
    bookmarks: "Saved",
    selectIdeaPrompt: "Select an idea to view details",
    adminOverview: "Admin Overview",
    adminSub: "System Management & Moderation",
    tableIdea: "Idea",
    tableAuthor: "Author",
    tableModeration: "Moderation Reply",
    tableAction: "Action",
    delete: "Delete",
    verify: "Verify",
    pwdHint: "Password: admin123",
    aiPromptLabel: "What do you want to brainstorm about?",
    aiInputPlaceholder: "E.g.: Green energy in the neighborhood...",
    aiThinking: "Gemini is thinking...",
    refineAI: "Refine with AI",
    adoptAI: "Develop this idea",
    titleLabel: "Title",
    categoryLabel: "Category",
    descLabel: "Description",
    authorLabel: "Author",
    shareTitle: "Share on Social Media",
    copyLink: "Copy Link",
    linkCopied: "Link copied!",
    draftSaved: "Draft auto-saved",
    categories: {
      [IdeaCategory.TECHNOLOGY]: "Technology",
      [IdeaCategory.COMMUNITY]: "Community",
      [IdeaCategory.SUSTAINABILITY]: "Sustainability",
      [IdeaCategory.EDUCATION]: "Education",
      [IdeaCategory.HEALTH]: "Health",
      [IdeaCategory.ART]: "Art",
      [IdeaCategory.INCLUSION]: "Inclusion"
    }
  },
  es: {
    dashboard: "Tablero",
    ideas: "Ideas",
    admin: "Admin",
    addIdea: "Añadir Idea",
    export: "Exportar (CSV)",
    search: "Buscar...",
    generateAI: "IA Brainstorm",
    submit: "Guardar Idea",
    titlePlaceholder: "Título de la idea",
    descPlaceholder: "Describe tu innovación...",
    authorPlaceholder: "Tu nombre",
    totalIdeas: "Ideas Totales",
    topCategory: "Categoría Principal",
    popularTitle: "Más Queridos",
    noIdeas: "No se encontraron ideas.",
    adminLogin: "Admin Login",
    adminActive: "Modo Admin Activo",
    deleteConfirm: "¿Estás seguro de que quieres eliminar esto?",
    adminReply: "Respuesta de Admin",
    replyPlaceholder: "Escribe una respuesta...",
    saveReply: "Guardar",
    topIdeasChart: "Top 5 Ideas Populares",
    timelineChart: "Ideas en el Tiempo",
    categoryChart: "Distribución por Categoría",
    engagement: "Compromiso Total",
    activeCategories: "Categorías Activas",
    sortBy: "Ordenar por:",
    newest: "Más nuevos",
    mostLoved: "Más amados",
    bookmarks: "Guardado",
    selectIdeaPrompt: "Selecciona una idea para ver detalles",
    adminOverview: "Resumen de Admin",
    adminSub: "Gestión y Moderación del Sistema",
    tableIdea: "Idea",
    tableAuthor: "Autor",
    tableModeration: "Respuesta de Moderación",
    tableAction: "Acción",
    delete: "Eliminar",
    verify: "Verificar",
    pwdHint: "Contraseña: admin123",
    aiPromptLabel: "¿Sobre qué quieres hacer un brainstorm?",
    aiInputPlaceholder: "Ej: Energía verde en el barrio...",
    aiThinking: "Gemini está pensando...",
    refineAI: "Refinar con IA",
    adoptAI: "Desarrollar esta idea",
    titleLabel: "Título",
    categoryLabel: "Categoría",
    descLabel: "Descripción",
    authorLabel: "Autor",
    shareTitle: "Compartir en Redes Sociales",
    copyLink: "Copiar Enlace",
    linkCopied: "¡Enlace copiado!",
    draftSaved: "Borrador guardado",
    categories: {
      [IdeaCategory.TECHNOLOGY]: "Tecnología",
      [IdeaCategory.COMMUNITY]: "Comunidad",
      [IdeaCategory.SUSTAINABILITY]: "Sostenibilidad",
      [IdeaCategory.EDUCATION]: "Educación",
      [IdeaCategory.HEALTH]: "Salud",
      [IdeaCategory.ART]: "Arte",
      [IdeaCategory.INCLUSION]: "Inclusión"
    }
  },
  de: {
    dashboard: "Dashboard",
    ideas: "Ideen",
    admin: "Admin",
    addIdea: "Idee hinzufügen",
    export: "Export (CSV)",
    search: "Suchen...",
    generateAI: "KI Brainstorm",
    submit: "Idee speichern",
    titlePlaceholder: "Ideentitel",
    descPlaceholder: "Beschreibe deine Innovation...",
    authorPlaceholder: "Dein Name",
    totalIdeas: "Ideen gesamt",
    topCategory: "Top-Kategorie",
    popularTitle: "Beliebteste",
    noIdeas: "Keine Ideen gefunden.",
    adminLogin: "Admin-Login",
    adminActive: "Admin-Modus aktiv",
    deleteConfirm: "Möchtest du das wirklich löschen?",
    adminReply: "Admin-Antwort",
    replyPlaceholder: "Antwort schreiben...",
    saveReply: "Speichern",
    topIdeasChart: "Top 5 Beliebte Ideen",
    timelineChart: "Ideen im Zeitverlauf",
    categoryChart: "Verteilung nach Kategorie",
    engagement: "Gesamt-Engagement",
    activeCategories: "Aktive Kategorien",
    sortBy: "Sortieren nach:",
    newest: "Neueste",
    mostLoved: "Beliebteste",
    bookmarks: "Gespeichert",
    selectIdeaPrompt: "Wähle eine Idee für Details",
    adminOverview: "Admin-Übersicht",
    adminSub: "Systemverwaltung & Moderation",
    tableIdea: "Idee",
    tableAuthor: "Autor",
    tableModeration: "Moderationsantwort",
    tableAction: "Aktion",
    delete: "Löschen",
    verify: "Verifizieren",
    pwdHint: "Passwort: admin123",
    aiPromptLabel: "Worüber möchtest du brainstormen?",
    aiInputPlaceholder: "Z.B.: Grüne Energie im Viertel...",
    aiThinking: "Gemini denkt nach...",
    refineAI: "Mit KI verfeinern",
    adoptAI: "Diese Idee ausarbeiten",
    titleLabel: "Titel",
    categoryLabel: "Kategorie",
    descLabel: "Beschreibung",
    authorLabel: "Autor",
    shareTitle: "Auf Social Media teilen",
    copyLink: "Link kopieren",
    linkCopied: "Link kopiert!",
    draftSaved: "Entwurf gespeichert",
    categories: {
      [IdeaCategory.TECHNOLOGY]: "Technologie",
      [IdeaCategory.COMMUNITY]: "Gemeinschaft",
      [IdeaCategory.SUSTAINABILITY]: "Nachhaltigkeit",
      [IdeaCategory.EDUCATION]: "Bildung",
      [IdeaCategory.HEALTH]: "Gezondheid",
      [IdeaCategory.ART]: "Kunst",
      [IdeaCategory.INCLUSION]: "Inklusion"
    }
  },
  ar: {
    dashboard: "لوحة القيادة",
    ideas: "الأفكار",
    admin: "الإدارة",
    addIdea: "إضافة فكرة",
    export: "تصدير (CSV)",
    search: "بحث...",
    generateAI: "عصف ذهني ذكي",
    submit: "حفظ الفكرة",
    titlePlaceholder: "عنوان الفكرة",
    descPlaceholder: "صف ابتكارك...",
    authorPlaceholder: "اسمك",
    totalIdeas: "إجمالي الأفكار",
    topCategory: "الفئة الأعلى",
    popularTitle: "الأكثر إعجاباً",
    noIdeas: "لم يتم العثور على أفكار.",
    adminLogin: "دخول المسؤول",
    adminActive: "وضع المسؤول نشط",
    deleteConfirm: "هل أنت متأكد من الحذف؟",
    adminReply: "رد الإدارة",
    replyPlaceholder: "اكتب رداً...",
    saveReply: "حفظ",
    topIdeasChart: "أفضل 5 أفكار",
    timelineChart: "الأفكار مع مرور الوقت",
    categoryChart: "توزيع الفئات",
    engagement: "إجمالي التفاعل",
    activeCategories: "الفئات النشطة",
    sortBy: "ترتيب حسب:",
    newest: "الأحدث",
    mostLoved: "الأكثر إعجاباً",
    bookmarks: "محفوظ",
    selectIdeaPrompt: "اختر فكرة لعرض التفاصيل",
    adminOverview: "نظرة عامة على الإدارة",
    adminSub: "إدارة النظام والاعتدال",
    tableIdea: "الفكرة",
    tableAuthor: "المؤلف",
    tableModeration: "رد الاعتدال",
    tableAction: "الإجراء",
    delete: "حذف",
    verify: "تحقق",
    pwdHint: "كلمة المرور: admin123",
    aiPromptLabel: "ما الذي تريد العصف الذهني حوله؟",
    aiInputPlaceholder: "مثال: الطاقة الخضراء في الحي...",
    aiThinking: "جيميني يفكر...",
    refineAI: "تحسين بالذكاء الاصطناعي",
    adoptAI: "تطوير هذه الفكرة",
    titleLabel: "العنوان",
    categoryLabel: "الفئة",
    descLabel: "الوصف",
    authorLabel: "المؤلف",
    shareTitle: "مشاركة على التواصل الاجتماعي",
    copyLink: "نسخ الرابط",
    linkCopied: "تم نسخ الرابط!",
    draftSaved: "تم حفظ المسودة",
    categories: {
      [IdeaCategory.TECHNOLOGY]: "تكنولوجيا",
      [IdeaCategory.COMMUNITY]: "مجتمع",
      [IdeaCategory.SUSTAINABILITY]: "استدامة",
      [IdeaCategory.EDUCATION]: "تعليم",
      [IdeaCategory.HEALTH]: "صحة",
      [IdeaCategory.ART]: "فن",
      [IdeaCategory.INCLUSION]: "شمول"
    }
  },
  zh: {
    dashboard: "仪表板",
    ideas: "想法",
    admin: "管理员",
    addIdea: "添加想法",
    export: "导出 (CSV)",
    search: "搜索...",
    generateAI: "AI 头脑风暴",
    submit: "保存想法",
    titlePlaceholder: "想法标题",
    descPlaceholder: "描述您的创新...",
    authorPlaceholder: "您的姓名",
    totalIdeas: "想法总数",
    topCategory: "热门类别",
    popularTitle: "最受欢迎",
    noIdeas: "未找到想法。",
    adminLogin: "管理员登录",
    adminActive: "管理模式已激活",
    deleteConfirm: "您确定要删除吗？",
    adminReply: "管理员回复",
    replyPlaceholder: "写下回复...",
    saveReply: "保存",
    topIdeasChart: "前5名热门想法",
    timelineChart: "想法随时间变化",
    categoryChart: "类别分布",
    engagement: "总参与度",
    activeCategories: "活跃类别",
    sortBy: "排序方式:",
    newest: "最新",
    mostLoved: "最受欢迎",
    bookmarks: "已收藏",
    selectIdeaPrompt: "选择一个想法查看详情",
    adminOverview: "管理员概览",
    adminSub: "系统管理与审核",
    tableIdea: "想法",
    tableAuthor: "作者",
    tableModeration: "审核回复",
    tableAction: "操作",
    delete: "删除",
    verify: "验证",
    pwdHint: "密码: admin123",
    aiPromptLabel: "您想针对什么进行头脑风暴？",
    aiInputPlaceholder: "例如：社区绿色能源...",
    aiThinking: "Gemini 正在思考...",
    refineAI: "使用 AI 优化",
    adoptAI: "开发此想法",
    titleLabel: "标题",
    categoryLabel: "类别",
    descLabel: "描述",
    authorLabel: "作者",
    shareTitle: "分享到社交媒体",
    copyLink: "复制链接",
    linkCopied: "链接已复制！",
    draftSaved: "草稿已保存",
    categories: {
      [IdeaCategory.TECHNOLOGY]: "技术",
      [IdeaCategory.COMMUNITY]: "社区",
      [IdeaCategory.SUSTAINABILITY]: "可持续性",
      [IdeaCategory.EDUCATION]: "教育",
      [IdeaCategory.HEALTH]: "健康",
      [IdeaCategory.ART]: "艺术",
      [IdeaCategory.INCLUSION]: "包容性"
    }
  },
  uk: {
    dashboard: "Панель приладів",
    ideas: "Ідеї",
    admin: "Адмін",
    addIdea: "Додати ідею",
    export: "Експорт (CSV)",
    search: "Пошук...",
    generateAI: "AI Мозковий штурм",
    submit: "Зберегти ідею",
    titlePlaceholder: "Назва ідеї",
    descPlaceholder: "Опишіть вашу інновацію...",
    authorPlaceholder: "Ваше ім'я",
    totalIdeas: "Всього ідей",
    topCategory: "Топ категорія",
    popularTitle: "Найпопулярніші",
    noIdeas: "Ідей не знайдено.",
    adminLogin: "Вхід для адміна",
    adminActive: "Режим адміна активний",
    deleteConfirm: "Ви впевнені, що хочете видалити це?",
    adminReply: "Відповідь адміністратора",
    replyPlaceholder: "Напишіть відповідь...",
    saveReply: "Зберегти",
    topIdeasChart: "Топ 5 популярних ідей",
    timelineChart: "Ідеї з часом",
    categoryChart: "Розподіл за категоріями",
    engagement: "Загальна активність",
    activeCategories: "Активні категорії",
    sortBy: "Сортувати за:",
    newest: "Найновіші",
    mostLoved: "Найулюбленіші",
    bookmarks: "Збережено",
    selectIdeaPrompt: "Виберіть ідею для перегляду деталей",
    adminOverview: "Огляд адмін-панелі",
    adminSub: "Управління системою та модерація",
    tableIdea: "Ідея",
    tableAuthor: "Автор",
    tableModeration: "Відповідь модератора",
    tableAction: "Дія",
    delete: "Видалити",
    verify: "Підтвердити",
    pwdHint: "Пароль: admin123",
    aiPromptLabel: "Про що ви хочете провести мозковий штурм?",
    aiInputPlaceholder: "Наприклад: Зелена енергія в районі...",
    aiThinking: "Gemini думає...",
    refineAI: "Покращити за допомогою AI",
    adoptAI: "Розвинути цю ідею",
    titleLabel: "Заголовок",
    categoryLabel: "Категорія",
    descLabel: "Опис",
    authorLabel: "Автор",
    shareTitle: "Поділитися у соцмережах",
    copyLink: "Копіювати посилання",
    linkCopied: "Посилання скопійовано!",
    draftSaved: "Чернетку збережено",
    categories: {
      [IdeaCategory.TECHNOLOGY]: "Технології",
      [IdeaCategory.COMMUNITY]: "Спільнота",
      [IdeaCategory.SUSTAINABILITY]: "Сталий розвиток",
      [IdeaCategory.EDUCATION]: "Освіта",
      [IdeaCategory.HEALTH]: "Здоров'я",
      [IdeaCategory.ART]: "Мистецтво",
      [IdeaCategory.INCLUSION]: "Інклюзія"
    }
  },
  fy: {
    dashboard: "Dashboard",
    ideas: "Ideeën",
    admin: "Behear",
    addIdea: "Idee Tafoegje",
    export: "Eksport (CSV)",
    search: "Sykje...",
    generateAI: "AI Brainstoarm",
    submit: "Idee Opslaan",
    titlePlaceholder: "Titel fan dyn idee",
    descPlaceholder: "Beskriuw dyn ynnovaasje...",
    authorPlaceholder: "Dyn namme",
    totalIdeas: "Totaal Ideeën",
    topCategory: "Top Kategory",
    popularTitle: "Meast Leafst",
    noIdeas: "Gjin ideeën fûn.",
    adminLogin: "Admin Ynlog",
    adminActive: "Behearmodus Aktyf",
    deleteConfirm: "Bisto wis datst dit fuortsmite wolst?",
    adminReply: "Behearder Reaksje",
    replyPlaceholder: "Skriuw in reaksje...",
    saveReply: "Opslaan",
    topIdeasChart: "Top 5 Populêre Ideeën",
    timelineChart: "Ideeën oer de Tiid",
    categoryChart: "Ferdieling per Kategory",
    engagement: "Totale Belutsenens",
    activeCategories: "Aktive Kategoryen",
    sortBy: "Sortearje op:",
    newest: "Nijste",
    mostLoved: "Meast Leafst",
    bookmarks: "Bewarre",
    selectIdeaPrompt: "Selektearje in idee foar details",
    adminOverview: "Behear Oersjoch",
    adminSub: "Systeembehear & Moderaasje",
    tableIdea: "Idee",
    tableAuthor: "Auteur",
    tableModeration: "Moderaasje Reaksje",
    tableAction: "Aksje",
    delete: "Fuortsmite",
    verify: "Ferifiearje",
    pwdHint: "Wachtwurd: admin123",
    aiPromptLabel: "Wêr wolst oer brainstoarmje?",
    aiInputPlaceholder: "Byv: Duorsume enerzjy yn de wyk...",
    aiThinking: "Gemini tinkt nei...",
    refineAI: "Ferbetterje mei AI",
    adoptAI: "Dit idee útstald",
    titleLabel: "Titel",
    categoryLabel: "Kategory",
    descLabel: "Beskriuwing",
    authorLabel: "Auteur",
    shareTitle: "Diel op Sosjale Media",
    copyLink: "Kopiearje Link",
    linkCopied: "Link kopiearre!",
    draftSaved: "Konsept bewarre",
    categories: {
      [IdeaCategory.TECHNOLOGY]: "Technology",
      [IdeaCategory.COMMUNITY]: "Mienskip",
      [IdeaCategory.SUSTAINABILITY]: "Duorsumens",
      [IdeaCategory.EDUCATION]: "Edukaasje",
      [IdeaCategory.HEALTH]: "Sûnens",
      [IdeaCategory.ART]: "Keunst",
      [IdeaCategory.INCLUSION]: "Inklúzje"
    }
  },
  fr: {
    dashboard: "Tableau de bord",
    ideas: "Idées",
    admin: "Admin",
    addIdea: "Ajouter une idée",
    export: "Exporter (CSV)",
    search: "Rechercher...",
    generateAI: "Brainstorming IA",
    submit: "Enregistrer l'idée",
    titlePlaceholder: "Titre de l'idée",
    descPlaceholder: "Décrivez votre innovation...",
    authorPlaceholder: "Votre nom",
    totalIdeas: "Total des idées",
    topCategory: "Top catégorie",
    popularTitle: "Les plus aimés",
    noIdeas: "Aucune idée trouvée.",
    adminLogin: "Connexion Admin",
    adminActive: "Mode Admin Activé",
    deleteConfirm: "Êtes-vous sûr de vouloir supprimer cela ?",
    adminReply: "Réponse de l'administrateur",
    replyPlaceholder: "Écrire une réponse...",
    saveReply: "Enregistrer",
    topIdeasChart: "Top 5 Idées Populaires",
    timelineChart: "Idées au fil du temps",
    categoryChart: "Répartition par catégorie",
    engagement: "Engagement total",
    activeCategories: "Catégories actives",
    sortBy: "Trier par :",
    newest: "Plus récent",
    mostLoved: "Plus aimé",
    bookmarks: "Enregistré",
    selectIdeaPrompt: "Sélectionnez une idée pour voir les détails",
    adminOverview: "Aperçu Admin",
    adminSub: "Gestion du système & modération",
    tableIdea: "Idée",
    tableAuthor: "Auteur",
    tableModeration: "Réponse de modération",
    tableAction: "Action",
    delete: "Supprimer",
    verify: "Vérifier",
    pwdHint: "Mot de passe : admin123",
    aiPromptLabel: "Sur quoi voulez-vous brainstormer ?",
    aiInputPlaceholder: "Ex : Énergie verte dans le quartier...",
    aiThinking: "Gemini réfléchit...",
    refineAI: "Affiner avec l'IA",
    adoptAI: "Développer cette idée",
    titleLabel: "Titre",
    categoryLabel: "Catégorie",
    descLabel: "Description",
    authorLabel: "Auteur",
    shareTitle: "Partager sur les réseaux sociaux",
    copyLink: "Copier le lien",
    linkCopied: "Lien copié !",
    draftSaved: "Brouillon enregistré",
    categories: {
      [IdeaCategory.TECHNOLOGY]: "Technologie",
      [IdeaCategory.COMMUNITY]: "Communauté",
      [IdeaCategory.SUSTAINABILITY]: "Durabilité",
      [IdeaCategory.EDUCATION]: "Éducation",
      [IdeaCategory.HEALTH]: "Santé",
      [IdeaCategory.ART]: "Art",
      [IdeaCategory.INCLUSION]: "Inclusion"
    }
  }
};
